openapi: 3.0.0
info:
  title: API Gateway
  version: "1.0"
  description: Minimal OpenAPI description for the API Gateway
paths:
  /api/movies:
    get:
      summary: Proxy to Inventory Service to get movies
      responses:
        "200":
          description: Successful response
  /api/billing:
    post:
      summary: Send a billing message via RabbitMQ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Successfully queued billing message
